---
title: "mpc_data_temp"
author: "kexin wang"
date: "10/9/2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(pdftools)
```

## READ & EXTYRACT 

```{r}
read <- function(pdf.file){
    require(dplyr)
    require(pdftools)
 
  # read in the pdf document; select the first page 
  pdfData <- pdf_data(pdf.file)
  p1Data <- pdfData[[1]]%>%group_by(y) 
  return(p1Data)

}

ex <- function(p1Data){
   # get the year and country from the header
  orderedData <- p1Data %>% 
  arrange(x, .by_group=TRUE)
  
  year <- orderedData$text[1]
  
  county <- orderedData %>% 
  summarize(line = paste(text, collapse=" ")) %>%
  slice(2) %>% select(line) %>% as.character()
  
  return(list(county, year))
}

#temp <- read(d_AG)
#ex(temp)[[1]]
```
## SLICE
```{r}
mod <- function(p1Data){
  county <- ex(p1Data)[[1]]
  year <- ex(p1Data)[[2]]
  
  cut <- p1Data %>% arrange(y) %>% summarize(n=n()) 
  
  if (county=="Prince Georges County, MD" | county=="Montgomery County, MD") {
  y.cut <- cut %>%
    slice(6) %>% select(y) %>% as.numeric()
  } 
  else {
    y.cut <- cut %>%
      slice(3) %>% select(y) %>% as.numeric()
  }
  
  p1Data <- p1Data %>% filter(y > y.cut + 1)%>%
  mutate(column=ifelse(x < 260, "Left", "Right"))
  # create the column variable (Left/Right)
  return(p1Data)
}
```
```{r}
temp <- mod(d_AG)
```

## GROUP

```{r}
gp <- function(p1Data){
  # group the data by column and height on the page
# keep the last entry of that column/height as the value
# assign the remaining entries for that column/height the name
  data <- p1Data %>% 
    group_by(column,y) %>% 
    arrange(x, .by_group=TRUE) %>%
    mutate(type = ifelse(x==max(x), 
                         "value", "name")) %>%
    summarize(variable = paste(text[type=="name"], 
                               collapse=" "), 
              count=text[type=="value"]) %>% 
    filter(count != "Calls", count!="exposure", count!="Site", count!="Outcome")
  
  return(data)
  
}

comb <- function(data, year, county){
  # create the data frame for this county/date
  myRow <- as.data.frame(t(as.numeric(data$count)))
  names(myRow) <- data$variable
  myRow$Year <- year
  myRow$County <- county

return(myRow)
  
}
```

```{r, warning=FALSE}
fna_1 <- function(file){
  p1Data <- read(file)
  county <- ex(p1Data)[[1]]
  year <- ex(p1Data)[[2]]
  
  d <- mod(p1Data)
  d <- gp(d)
  d <- comb(d, year, county)
  
  return(d)
}
```

```{r}
t1 <- read("Prince Georges County Statistical Report 2018.pdf") 
ex(t1)

t1 <- mod(t1)
t1 <- t1 %>% 
    group_by(column,y) %>% 
    arrange(x, .by_group=TRUE) %>%
    mutate(type = ifelse(x==max(x), 
                         "value", "name")) %>%
    summarize(variable = paste(text[type=="name"], 
                               collapse=" "), 
              count=text[type=="value"])
t1 %>%  filter(count != c("Calls","exposure","Site" ,"Outcome"))
```


```{r}
fna_1("Prince Georges County Statistical Report 2018.pdf")
fna_1("Allegany County Statistical Report 2018.pdf")
fna_1("Talbot County Statistical Report 2018.pdf")
```


```{r}
files = list.files(path='./data',pattern="*.pdf")
files
```

```{r}

d1 <- fna_1(paste0("./data/",files[1]))
Data <- d1

options(warn=2)
for (i in 2:length(files)) {
  di <- fna_1(paste0("./data/",files[i]))
  Data <- bind_rows(Data,di)
  print(i)
}


```